=== mitica/product-selectors/schema-01.json
{
  "$schema": "http://json-schema.org/draft-07/schema",

  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "const": "01",
      "description": "Schema version"
    },
    "url": { "type": "string", "format": "url" },
    "name": { "type": "string", "minLength": 2, "maxLength": 50 },
    "country": { "type": "string", "pattern": "^[a-z]{2}$" },
    "currency": { "type": "string", "pattern": "^[A-Z]{3}$" },
    "lists": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "language": { "type": "string", "pattern": "^[a-z]{2}$" },
          "currency": { "type": "string", "pattern": "^[A-Z]{3}$" },
          "list": { "$ref": "#/definitions/productList" }
        },
        "required": ["language", "list"]
      },
      "uniqueItems": true,
      "maxItems": 100
    },
    "products": {
      "type": "array",
      "items": { "$ref": "#/definitions/productItem" },
      "uniqueItems": true,
      "maxItems": 100
    }
  },
  "required": ["version", "url", "name", "country"],
  "additionalProperties": true,

  "definitions": {
    "productItem": {
      "type": "object",
      "properties": {
        "urlPattern": { "type": "string" },
        "product": {
          "$ref": "#/definitions/productSelector"
        }
      },
      "required": ["product"]
    },

    "productList": {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Optional list name." },
        "productType": { "$ref": "#/definitions/productType" },
        "url": { "type": "string", "format": "url" },
        "paginate": { "$ref": "#/definitions/paginate" },
        "item": { "$ref": "#/definitions/selector" },
        "product": {
          "$ref": "#/definitions/productSelector",
          "required": ["url"]
        }
      },
      "required": ["productType", "url", "item", "product"]
    },

    "productType": { "type": "string", "enum": ["smartphone"] },

    "paginate": {
      "type": "object",
      "properties": {
        "next": { "$ref": "#/definitions/selector" },
        "limit": { "type": "integer", "minimum": 0 }
      },
      "required": ["next"]
    },

    "productSelector": {
      "type": "object",
      "properties": {
        "url": { "$ref": "#/definitions/selector" },
        "title": { "$ref": "#/definitions/selector" },
        "description": { "$ref": "#/definitions/selector" },
        "image": { "$ref": "#/definitions/selector" },
        "price": { "$ref": "#/definitions/priceSelector" },
        "currency": { "$ref": "#/definitions/selector" }
      },
      "required": ["title", "price"]
    },

    "priceSelector": {
      "oneOf": [
        { "$ref": "#/definitions/selector" },
        {
          "type": "object",
          "properties": {
            "price": { "$ref": "#/definitions/selector" },
            "integerPart": { "$ref": "#/definitions/selector" },
            "decimalPart": { "$ref": "#/definitions/selector" }
          },
          "oneOf": [
            { "required": ["price"] },
            { "required": ["integerPart", "decimalPart"] }
          ]
        }
      ]
    },

    "selector": { "type": "string" }
  }
}

=== mitica/product-selectors/data/ro/altex.json
{
  "$schema": "../../schema-01.json",
  "version": "01",
  "country": "ro",
  "name": "Altex",
  "url": "https://www.altex.ro/",
  "currency": "RON",

  "lists": [
    {
      "language": "ro",
      "list": {
        "name": "Best sale",
        "productType": "smartphone",
        "url": "https://altex.ro/telefoane/cpl/filtru/p/1/",
        "paginate": {
          "next": ".Toolbar .Toolbar-pager a.Button--forSelect@href"
        },
        "item": "ul.Products li.Products-item",
        "product": {
          "url": "a.Product-photoTrigger@href",
          "title": "a.Product-photoTrigger@title",
          "image": "img.Product-photo@src",
          "price": {
            "integerPart": ".Price-int | digits | integer",
            "decimalPart": ".Price-dec | digits | integer"
          }
        }
      }
    }
  ]
}
